experiments:
  lstm_model:
    - version: '1.0'
      dataset_path: './src/data/postprocessed_HAR_dataset'
      model:
        in_features: 9
        num_classes: 6
        lstm_layers: [256, 128]
        fc_layers: [256, 128]
      training:
        epochs: 1
        batch_size: 32
        learning_rate: 0.001

    - version: '2.0'
      dataset_path: './src/data/postprocessed_HAR_dataset'
      model:
        in_features: 9
        num_classes: 6
        lstm_layers: [256, 128]
        fc_layers: [256, 128, 64]
      training:
        epochs: 10
        batch_size: 64
        learning_rate: 0.001
